services:
  server:
    container_name: server
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: always
    expose:
      - '5050'
    volumes:
      - ./server/logs:/usr/src/app/logs:rw
      - ./server/uploads:/usr/src/app/uploads:rw
    depends_on:
      - mongo-staging
      - redis
    networks:
      - test-network

  mongo-staging:
    container_name: mongo-staging
    image: mongo:latest
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: staging_db
    volumes:
      - mongo-staging-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - test-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - test-network

volumes:
  mongo-staging-data:

networks:
  test-network:
