services:
  server:
    container_name: server
    environment:
      - NODE_ENV=production
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: always
    expose:
      - '5050'
    volumes:
      - ./server/logs:/usr/src/app/logs:rw
      - ./server/uploads:/usr/src/app/uploads:rw
    depends_on:
      - mongo-production
      - redis
    networks:
      - prod-network

  mongo-production:
    container_name: mongo-production
    image: mongo:latest
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: production_db
    volumes:
      - mongo-production-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - prod-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - prod-network

volumes:
  mongo-production-data:

networks:
  prod-network:
